@endpoint=http://localhost:5239/products

###

GET {{endpoint}}

###

GET {{endpoint}}/1


###

POST {{endpoint}}
Content-Type: application/json

{
  "name": "Product 1",
  "price": 100
}

###

PUT {{endpoint}}/1
Content-Type: application/json

{
  "name": "My 1",
  "price": 100
}

###

DELETE {{endpoint}}/1
